spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: AUTHENTICATION-SERVICE
server:
  port: 8182
  error:
    include-message: always